baseURL: 'https://toddeddy.com'
title: Todd Eddy
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
enableEmoji: true
enableGitinfo: false
# Enable Disqus comments
# disqusShortname: yourdiscussshortname

markup:
  highlight:
    #style: github-dark
    style: solarized-dark
  goldmark:
    renderer:
      unsafe: true

pagination:
  pagerSize: 20

params:
  author: Todd Eddy
  #license: >-
  # <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC
  # BY-SA-4.0</a>
  description: Todd Eddy's personal website
  keywords: 'blog,developer,personal'
  info:
    - Site Reliability Engineer (SRE)
    - Linux Guru
    - Maker
  avatarURL: images/avatar.png
  #gravatar: todd@toddeddy.com
  dateFormat: 'January 2, 2006'
  #since: 2019
  # Git Commit in Footer, uncomment the line below to enable it
  #commit: 'https://github.com/luizdepra/hugo-coder/tree/'
  # Right To Left, shift content direction for languagues such as Arabic
  rtl: false
  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorScheme: 'auto'
  # Hide the toggle button, along with the associated vertical divider
  hideColorSchemeToggle: false
  # Series see also post count
  maxSeeAlsoItems: 5

  # Custom CSS
  customCSS: []

  # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
  customSCSS: []

  # Custom JS
  customJS: []

  # Custom remote JS files
  customRemoteJS: []

  # If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
  goatCounter:
    code: "vrillusions"


# NOTE you'll need to migrate any of these over to yaml format
# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to use Pirsch(https://pirsch.io) for analytics, add this section
# [params.pirsch]
# code = "ABCDE"

# If you want to implement a Content-Security-Policy, add this section
# NOTE: this is being handled in nginx config
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]
# Kept around TOML version because the YAML one looks weird and may not be needed
#  csp:
#    childsrc:
#      - '''self'''
#    fontsrc:
#      - '''self'''
#      - 'https://fonts.gstatic.com'
#      - 'https://cdn.jsdelivr.net/'
#    formaction:
#      - '''self'''
#    framesrc:
#      - '''self'''
#      - 'https://www.youtube.com'
#    imgsrc:
#      - '''self'''
#    objectsrc:
#      - '''none'''
#    stylesrc:
#      - '''self'''
#      - '''unsafe-inline'''
#      - 'https://fonts.googleapis.com/'
#      - 'https://cdn.jsdelivr.net/'
#    scriptsrc:
#      - '''self'''
#      - '''unsafe-inline'''
#      - 'https://www.google-analytics.com'
#      - 'https://cdn.jsdelivr.net/'
#    prefetchsrc:
#      - '''self'''
#    connectsrc:
#      - '''self'''
#      - 'https://www.google-analytics.com'

# icon list (unsure how to figure out what version this has): https://forkaweso.me/Fork-Awesome/icons/
#
  social:
    - name: Github
      icon: fa fa-2x fa-brands fa-github
      weight: 20
      url: 'https://github.com/vrillusions/'

    - name: Twitter
      icon: fa fa-2x fa-brands fa-x-twitter
      weight: 30
      url: 'https://twitter.com/vrillusions/'

    - name: Mastodon
      icon: fa fa-2x fa-brands fa-mastodon
      weight: 31
      # used for mastodon to mark it as verified link
      rel: me
      url: 'https://mastodon.online/@vrillusions'

    - name: Bluesky
      icon: fa fa-2x fa-brands fa-bluesky
      weight: 32
      rel: me
      url: 'https://bsky.app/profile/vrillusions.bsky.social'

    - name: Keybase
      icon: fa fa-2x fa-brands fa-keybase
      weight: 30
      url: 'https://keybase.io/vrillusions'

    - name: LinkedIn
      icon: fa fa-2x fa-brands fa-linkedin
      weight: 40
      url: 'https://www.linkedin.com/in/toddeddy/'

    # no polywork icon
    #- name: Timeline
    #  icon: fa fa-2x fa-polywork
    #  weight: 41
    #  url: 'https://timeline.toddeddy.com/'

    #- name: RSS
    #  icon: fa fa-2x fa-rss
    #  weight: 999
    #  url: 'https://myhugosite.com/index.xml'
    #  rel: alternate
    #  type: application/rss+xml


taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          weight: 1
          url: about/
        #- name: Blog
        #  weight: 2
        #  url: posts/
        #- name: Projects
        #  weight: 3
        #  url: projects/
        - name: Contact me
          weight: 5
          url: contact/

outputs:
  home: ['HTML']
  page: ['HTML']
  section: ['HTML']
  taxonomy: ['HTML']
  term: ['HTML']
